---
- name: Update yum cache
  become: true
  register: yum_check_update_result
  command: yum check-update
  changed_when: "yum_check_update_result.rc == 100"
  failed_when: "yum_check_update_result.rc != 0 and yum_check_update_result.rc != 100"

- name: Install Python3
  become: true
  command: yum install -y python3 python3-pip
  register: yum_result
  changed_when: "'Nothing to do' not in yum_result.stdout"
