---
- name: Delete libvirt snapshot
  hosts: "{{ libvirt_host | default('libvirt') }}"
  vars_prompt:
    - name: snapshot_name
      prompt: "Snapshot name"
      private: no

    - name: libvirt_domains
      prompt: "Libvirt domain(s) (separate by ' ' or ',')"
      private: no

  vars:
    libvirt_vm_uri: "qemu:///system"

    # Variables to add to the enviroment that is used to execute virsh commands
    libvirt_vm_script_env: "{{  { 'LIBVIRT_DEFAULT_URI': libvirt_vm_uri } if libvirt_vm_uri else {} }}"

  tasks:
    - set_fact:
        libvirt_domain_list: "{{ (libvirt_domains | default('')).strip().replace(' ',',').split(',') | list }}"

    - name: Delete snapshot
      environment: "{{ libvirt_vm_script_env }}"
      command: >
        virsh snapshot-delete
        --domain {{ item | quote }}
        --snapshotname  {{ snapshot_name | quote }}
      loop: "{{ libvirt_domain_list }}"
      register: delete_snapshot_r

    - set_fact:
        deleted_snapshots: {}

    - set_fact:
        deleted_snapshots: "{{ deleted_snapshots | combine({item.item: item.stdout_lines}) }}"
      loop: "{{ delete_snapshot_r.results }}"

    - debug:
        var: deleted_snapshots
